spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://usagi-mysql:3306/usagi?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql://localhost:3306/usagi
    password: "UsagiLByH7CW2BD8szH7WPy"
#    password: 1234
    username: "usagi"
#    username: "root"
  data:
    redis:
      port: 6379
      host: usagi-redis
#      host: localhost
      password: "UsagiLByBD8szH7CWPy"
#      password: 1234
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
  sql:
    init:
      schema-locations:
        - classpath:/init-database.sql
      data-locations:
        - classpath:/init-data.sql
      continue-on-error: true
      encoding: utf-8
      mode: always

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # output mybatis log to console
    map-underscore-to-camel-case: true # map underscore to camel case

flag-seed: 'DONATEFORCHIIKAWA'